
# Adds namespace to all resources.
namespace:  mochi-mqtt

resources:
- ./namespace.yaml
- ./deployment.yaml
- ./service.yaml
- ./route.yaml

images:
- name: quay.io/skeeey/mochimqtt:latest
  newName: quay.io/skeeey/mochimqtt
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- name: mochi-mqtt-certs
  files:
  - root-ca.pem
  - server.pem
  - server-key.pem
